# Generated by Django 3.0.6 on 2020-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200530_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='pais',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
